version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    rebase-strategy: "disabled"
    labels:
      - kind/enhancement
      - release-note/misc