kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terway-qos
  labels:
    {{- include "terway-qos.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  verbs:
  - get
  - watch
  - list
