apiVersion: v1
kind: ServiceAccount
metadata:
  name: terway-qos
  labels:
    {{- include "terway-qos.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

